# Generated by Django 5.2.3 on 2025-07-03 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailings", "0002_mailing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailingattempt",
            name="emails_sent",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
